crowd_funding/category/urls.py
from django.urls import path
from .views import add_category, show_categories, edit_category
app_name = "category"
urlpatterns = [
    path('add/', add_category, name='add_category'),
    path('show_categories/', show_categories, name='show_categories'),
    path('edit/<int:pk>', edit_category, name='edit_category'),


]

crowd_funding/crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, show_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('user_profile.urls')),
    path('category/', include('category.urls')),
    path('project/', include('project.urls')),
    path('comment/', include('comment.urls')),
    path('donation/', include('donation.urls')),
    path('rate/', include('rate.urls')),
    path('', home, name='home'),
    path('search/', show_projects, name='search')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowd_funding/project/urls.py
from django.urls import path
from .views import (
    add_project,
    show_project,
    report_project,
)
app_name = "project"
urlpatterns = [
    path('add/', add_project, name='add_project'),
    path('show/<int:pk>', show_project, name='show_project'),
    path('report/<int:pk>', report_project, name='report_project'),

]

crowd_funding/rate/urls.py
from django.urls import path
from .views import (
    add_rate
)
app_name = "rate"
urlpatterns = [
    path('add/<int:pk>', add_rate, name='add_rate'),

]

crowd_funding/user_profile/urls.py
from django.urls import path
from .views import (
    user_login,
    user_logout,
    user_register,
    show_profile,
    edit_profile,
    activate,
)
app_name = "user_profile"
urlpatterns = [
    path('login/', user_login, name='user_login'),
    path('logout/', user_logout, name='user_logout'),
    path('register/', user_register, name='user_register'),
    path('user/<int:pk>/', show_profile, name='show_profile'),
    path('edit/<int:pk>/', edit_profile, name='edit_profile'),
    path('activate/<slug:uidb64>/<slug:token>/', activate, name='activate')
]

crowd_funding/user_profile/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
#profiles (id (pk), title, user_id (fk) (1:1), imgs, phone, email, birth_date, facebook_link, country )
class user_profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True,)
    phone = models.CharField(max_length=11, blank=True)
    img = models.ImageField()
    birth_date = models.DateField(null=True, blank=True)
    facebook_link = models.URLField(max_length=200, null=True, blank=True)
    country = models.CharField(max_length=20, null=True, blank=True)

    def __str__(self):
        return f'user name: {self.user} telephone number: {self.phone}'
    
    

crowd_funding/user_profile/forms.py
from django import forms
import datetime
class Register_form(forms.Form):
    username = forms.CharField(label=False, max_length=150,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': 'Username',
                                                             }))
    first_name = forms.CharField(label=False,
                                 widget=forms.TextInput(attrs={'class': 'form-control',
                                                               'placeholder': 'First Name',
                                                               }))
    last_name = forms.CharField(label=False,
                                widget=forms.TextInput(attrs={'class': 'form-control',
                                                              'placeholder': 'Last Name',
                                                              }))
    email = forms.EmailField(label=False,
                             widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'placeholder': 'Email',
                                                           }))
    password = forms.CharField(label=False, max_length=50,
                               widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                 'placeholder': 'Password',
                                                                 }))
    confirm_password = forms.CharField(label=False, max_length=50,
                                       widget=forms.PasswordInput(attrs={'class': 'form-control',
                                                                         'placeholder': 'Confirm password',
                                                                         }))
    phone = forms.CharField(label=False, max_length=11,
                            widget=forms.TextInput(attrs={'class': 'form-control',
                                                          'placeholder': 'Phone',
                                                          'pattern': '^01[0-2]\d{1,8}$',
                                                          }))
    img = forms.ImageField(label='Enter Photo(.PNG , .JPG)',
                           widget=forms.FileInput(attrs={'class': 'form-control',
                                                         }))

    birth_date = forms.DateField(label='Birth date', required=False,
                                 widget=forms.DateInput(attrs={'class': 'form-control datetimepicker-input',
                                                               'type': 'date',
                                                               }), )
    facebook_link = forms.URLField(label=False, required=False, max_length=200,
                                   widget=forms.URLInput(attrs={'class': 'form-control',
                                                                'placeholder': 'Facebook link',
                                                                }))

    country = forms.CharField(label=False, required=False, max_length=20,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': 'Country',
                                                            }))

    def clean(self):
        password1 = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('confirm_password')

        if password1 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")

        return self.cleaned_data

crowd_funding/user_profile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import Register_form
from django.contrib.auth.models import User
from .models import user_profile
from django.db.models import Q
from project.models import Project
from donation.models import Donation

#from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.contrib.sites.models import Site


# Create your views here.


# login function
def user_login(request):
    # when request POST
    if request.POST:
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)

    return redirect('home')


# logout function
@login_required
def user_logout(request):
    logout(request)
    return redirect('home')



def activate(request, uidb64, token, backend='django.contrib.auth.backends.ModelBackend'):
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user, backend='django.contrib.auth.backends.ModelBackend')
        return redirect('home')
    else:
        return redirect('home')
# register function
def user_register(request):
    if request.user.is_authenticated:
        return redirect('home')

    if request.POST:
        data = request.POST
        form = Register_form(request.POST, request.FILES)
        if form.is_valid():
            # create new user
            valid_user = User.objects.filter(Q(username=data['username']) | Q(email=data['email']))
            if len(valid_user) > 0:
                print(valid_user)
                return render(request, "user_profile/register.html", {'form': form,
                                                                      'msg': "enter valid username or email"})
            user = User.objects.create_user(username=data['username'],
                                            first_name=data['first_name'],
                                            last_name=data['last_name'],
                                            email=data['email'],
                                            password=data['password'],
                                            )
            user.is_active = False
            user.save()
            profile = user_profile.objects.create(user=user,
                                                  phone=data['phone'],
                                                  facebook_link=data['facebook_link'],
                                                  country=data['country'],
                                                  img=request.FILES['img'],
                                                  )
            current_site = Site.objects.get_current()
            print(current_site.domain)
            mail_subject = 'Activate your blog account.'
            message = render_to_string('acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            to_email = form.cleaned_data.get('email')
            email = EmailMessage(
                mail_subject, message, to=[to_email]
            )
            email.send()
            return redirect('home')

            # create new profile


            if data['birth_date'] is not None:
                profile.birth_date = data['birth_date']
            return redirect('home')
        else:
            # redirect to the same page
            return render(request, "user_profile/register.html", {'form': form})
    else:
        form = Register_form()
        return render(request, "user_profile/register.html", {'form': form})


# show profile
def show_profile(request, pk):
    try:
        user = User.objects.filter(pk=pk).first()
        projects = Project.objects.filter(user=user)
        profile = user_profile.objects.filter(user=user).first()
        donations = Donation.objects.filter(user=user)
        if profile:
            return render(request, 'user_profile/profile.html', {'profile': profile,
                                                                 'projects': projects,
                                                                 'donations': donations})
        else:
            return redirect('home')

    except:
        return redirect('home')


# edit profile
@login_required
def edit_profile(request, pk):
    try:
        if request.POST:
            # pk for profile not user
            data = request.POST
            profile = user_profile.objects.filter(pk=pk).first()
            if profile.user.pk == request.user.pk:
                if request.FILES.get('img1'):
                    profile.img = request.FILES.get('img1')
                if data['first_name']:
                    profile.user.first_name = data['first_name']
                if data['last_name']:
                    profile.user.last_name = data['last_name']
                if data['phone']:
                    profile.phone = data['phone']
                if data['country']:
                    profile.country = data['country']
                if data['facebook_url']:
                    profile.facebook_link = data['facebook_url']
                if data['birth_date']:
                    profile.birth_date = data['birth_date']
                profile.user.save()
                profile.save()

            return redirect('user_profile:show_profile', pk=profile.user.pk)
        else:

            return redirect('home')

    except:

        return redirect('home')

crowd_funding/templates/acc_active_email.html
{% autoescape off %}
Hi {{ user.username }},
Please click on the link to confirm your registration,
http://127.0.0.1:8000{% url 'user_profile:activate' uidb64=uid token=token %}
{% endautoescape %}

crowd_funding/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{% block title %} {% endblock %}</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
    integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous" />
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
    integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
    crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
    integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
    integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.0/font/bootstrap-icons.css" />
  <style>
    .form-control {
      box-shadow: none;
      font-weight: normal;
      font-size: 13px;
    }

    .navbar .form-inline {
      display: inline-block;
    }

    .navbar a {
      color: #888;
      font-size: 15px;
    }

    .navbar .sign-up-btn {
      min-width: 110px;
      max-height: 36px;
    }

    .navbar .dropdown-menu {
      color: #999;
      font-weight: normal;
      border-radius: 1px;
      border-color: #e5e5e5;
      box-shadow: 0 2px 8px rgba(0, 0, 0, .05);
    }

    .navbar a,
    .navbar a:active {
      color: #888;
      padding: 8px 20px;
      background: transparent;
      line-height: normal;
    }

    .navbar .navbar-form {
      border: none;
    }

    .navbar .action-form {
      width: 280px;
      padding: 20px;
      left: auto;
      right: 0;
      font-size: 14px;
    }

    .navbar .action-form a {
      color: #33cabb;
      padding: 0 !important;
      font-size: 14px;
    }

    .navbar .action-form .hint-text {
      text-align: center;
      margin-bottom: 15px;
      font-size: 13px;
    }

    .navbar .btn-primary,
    .navbar .btn-primary:active {
      color: #fff;
      background: #33cabb !important;
      border: none;
    }

    .navbar .btn-primary:hover,
    .navbar .btn-primary:focus {
      color: #fff;
      background: #31bfb1 !important;
    }

    .navbar .social-btn .btn,
    .navbar .social-btn .btn:hover {
      color: #fff;
      margin: 0;
      padding: 0 !important;
      font-size: 13px;
      border: none;
      transition: all 0.4s;
      text-align: center;
      line-height: 34px;
      width: 47%;
      text-decoration: none;
    }

    .navbar .social-btn .facebook-btn {
      background: #507cc0;
    }

    .navbar .social-btn .facebook-btn:hover {
      background: #4676bd;
    }

    .navbar .social-btn .twitter-btn {
      background: #64ccf1;
    }

    .navbar .social-btn .twitter-btn:hover {
      background: #4ec7ef;
    }

    .navbar .social-btn .btn i {
      margin-right: 5px;
      font-size: 16px;
      position: relative;
      top: 2px;
    }

    .or-seperator {
      margin-top: 32px;
      text-align: center;
      border-top: 1px solid #e0e0e0;
    }

    .or-seperator b {
      color: #666;
      padding: 0 8px;
      width: 30px;
      height: 30px;
      font-size: 13px;
      text-align: center;
      line-height: 26px;
      background: #fff;
      display: inline-block;
      border: 1px solid #e0e0e0;
      border-radius: 50%;
      position: relative;
      top: -15px;
      z-index: 1;
    }
  </style>
  {% block head %}
    {% endblock %}
</head>

<body>
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-light col-xl-12 col-lg-12 col-md-12 col-sm-12">
    <a class="navbar-brand" href="/">Funding Site</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {%if request.user.is_superuser%}
    <div class="nav-item">
          <a href="{% url 'category:add_category'%}"  class="btn btn-primary  sign-up-btn">Add Category</a>
    </div>
    {%endif%}

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto"></ul>
      <form style="margin-right: 300px" method="GET" action="{% url 'search'%}" class="form-inline my-2 my-lg-0">

        <input style="width: 400px" class="form-control mr-sm-2" type="search" placeholder="Search" name="q"
          aria-label="Search" />
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">
          Search
        </button>
      </form>
      {% if request.user.is_authenticated%}
      <div class="navbar-nav ml-auto">
			<div class="nav-item dropdown">
			  <div
			   data-toggle="dropdown" class="nav-link dropdown-toggle user-action avatar"> {{ user.get_username }}  <b class="caret"></b></div>
			  <div class="dropdown-menu">
				<a href="{% url 'user_profile:show_profile' request.user.id%}" class="dropdown-item"><i class="bi bi-person-check-fill"></i> Profile</a></a>
				<div class="dropdown-divider"></div>
				<a href="{% url 'user_profile:user_logout'%}" class="dropdown-item"><i class="bi bi-box-arrow-right"></i> Logout</a></a>
			  </div>
			</div>
		  </div>
      {% else%}
      <div class="navbar-nav ml-auto action-buttons">
        <div class="nav-item dropdown">
          <a href="#" data-toggle="dropdown" class="nav-link dropdown-toggle mr-4">Login</a>
          <div class="dropdown-menu action-form">
            <form action="{% url 'user_profile:user_login'%}" method="POST">
              {% csrf_token %}
              <p class="hint-text">Sign in with your social media account</p>
              <div class="form-group social-btn clearfix">
                <a href="#" class="btn btn-secondary facebook-btn float-left"><i class="fa fa-facebook"></i>
                  Facebook</a>
                <a href="#" class="btn btn-secondary twitter-btn float-right"><i class="fa fa-twitter"></i> Twitter</a>
              </div>
              <div class="or-seperator"><b>or</b></div>
              <div class="form-group">
                <input type="text" class="form-control" name='username' placeholder="Username" required="required">
              </div>
              <div class="form-group">
                <input type="password" class="form-control" name='password' placeholder="Password" required="required">
              </div>
              <input type="submit" class="btn btn-primary btn-block" value="Login">
              <div class="text-center mt-2">
                <a href="#">Forgot Your password?</a>
              </div>
            </form>
          </div>
        </div>
        <div class="nav-item dropdown">
          <a href="{% url 'user_profile:user_register'%}"  class="btn btn-primary  sign-up-btn">Sign up</a>

        </div>

      </div>
      {% endif %}

      </div>
  </nav>
  <!-- Navbar -->
  <!--container-->
  {%if bad_alert%}
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    {{bad_alert}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {%endif%}
  {%if good_alert%}
  <div class="alert alert-success alert-dismissible fade show" role="alert">
  {{good_alert}}
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
  {%endif%}

    {% block contain %}
    {% endblock %}

  <!-- Footer -->
  <footer style="transform: translateY(90px)" class="bg-dark text-center text-white mt-5">
    <!-- Grid container -->
    <div class="col-auto">
      <p class="pt-5">
        <strong>Connect with us:</strong>
      </p>
    </div>
    <div class="container pb-4">
      <!-- Section: Social media -->
      <section class="mb-4">
        <!-- Facebook -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-facebook"></i></a>

        <!-- Twitter -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-twitter"></i></a>

        <!-- Google -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-google"></i></a>

        <!-- Instagram -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-instagram"></i></a>

        <!-- Linkedin -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-linkedin"></i></a>

        <!-- Github -->
        <a class="btn btn-outline-light btn-floating m-1" href="#!" role="button"><i class="bi bi-github"></i></a>
      </section>
      <!-- Section: Social media -->

      <!-- Section: Form -->
      <section class="">
        <form action="">
          <!--Grid row-->
          <div class="row d-flex justify-content-center">
            <!--Grid column-->
            <div class="col-auto">
              <p class="pt-2">
                <strong>Sign up for our newsletter</strong>
              </p>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-md-5 col-12">
              <!-- Email input -->
              <div class="form-outline form-white mb-4">
                <input type="email" id="form5Example2" class="form-control" />

              </div>
            </div>
            <!--Grid column-->

            <!--Grid column-->
            <div class="col-auto">
              <!-- Submit button -->
              <button type="submit" class="btn btn-outline-primary mb-4">
                Subscribe
              </button>
              <button type="submit" class="btn btn-outline-success mb-4">
                Send Feadback
              </button>
            </div>
            <!--Grid column-->
          </div>
          <!--Grid row-->
        </form>
      </section>
      <!-- Section: Form -->
      <!-- Section: Links -->
      <section class="">
        <!--Grid row-->
        <div class="row">
          <!--Grid column-->
          <div class="col-lg-6 col-md-6 ">
            <h5 class="text-uppercase">Follow Links</h5>
            <ul class="list-unstyled mb-0">
              <li>
                <a href="#!" class="text-white">About Us</a>
              </li>
              <li>
                <a href="#!" class="text-white">Blog</a>
              </li>
              <li>
                <a href="#!" class="text-white text-left">FAQ</a>
              </li>
              <li>
                <a href="#!" class="text-white">Terms of Service </a>
              </li>
              <li>
                <a href="#!" class="text-white "> Partnerships </a>
              </li>
            </ul>
          </div>
          <!--Grid column-->

          <!--Grid column-->
          <div class="col-lg-6 col-md-6 ">
            <h5 class="text-uppercase">Contact us:</h5>
            <ul class="list-unstyled mb-0">
              <li class="bi bi-telephone-fill">

                <a class="text-white">Phone</a>
              </li>
              <li>
                <a class="text-white fa fa-phone">720-570-1702</a>
              </li>
              <li class="bi bi-envelope-fill">
                <a class="text-white">Email</a>
              </li>
              <li class="bi bi-email">
                <a class="text-white">info@funding.com</a>
              </li>
            </ul>
          </div>
          <!--Grid column-->
        </div>
        <!--Grid row-->
      </section>
      <!-- Section: Links -->
    </div>
    <!-- Grid container -->

    <!-- Copyright -->
    <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
      © 2021 Copyright:
      <a class="text-white" href="#">FundingSite.com</a>
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer -->
   {% block script %}
    {% endblock %}
</body>

</html>