crowd_funding/category/urls.py
from django.urls import path
from .views import add_category, show_categories, edit_category
app_name = "category"
urlpatterns = [
    path('add/', add_category, name='add_category'),
    path('show_categories/', show_categories, name='show_categories'),
    path('edit/<int:pk>', edit_category, name='edit_category'),


]

crowd_funding/crowd_funding/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, show_projects

urlpatterns = [
    path('admin/', admin.site.urls),
    path('profile/', include('user_profile.urls')),
    path('category/', include('category.urls')),
    path('project/', include('project.urls')),
    path('comment/', include('comment.urls')),
    path('donation/', include('donation.urls')),
    path('rate/', include('rate.urls')),
    path('', home, name='home'),
    path('search/', show_projects, name='search')

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

crowd_funding/rate/urls.py
from django.urls import path
from .views import (
    add_rate
)
app_name = "rate"
urlpatterns = [
    path('add/<int:pk>', add_rate, name='add_rate'),

]

crowd_funding/category/models.py
from django.db import models
from django.conf import settings
# Create your models here.
#categories ( id (pk), categ_name )
class Category(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    name = models.CharField(max_length=20)

    def __str__(self):
        return self.name

crowd_funding/category/forms.py
from django import forms
import datetime
class Category_form(forms.Form):
    name = forms.CharField(label=False, max_length=150,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': 'Add category name',
                                                         }))

crowd_funding/category/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required, permission_required
from .forms import Category_form
from .models import Category
# Create your views here.


@login_required
@permission_required('is_superuser')
def add_category(request):
    if request.POST:
        data = request.POST
        form = Category_form(request.POST)
        if form.is_valid():
            category = Category.objects.create(name=data['name'], user=request.user)
            form = Category_form()
            return render(request, "category/add_category.html", {'good_alert': "Category Created successfully you can create another category",
                                                                  'form': form})
        else:
            # redirect to the same page
            return render(request, "category/add_category.html", {'bad_alert': "failed to create category try again",
                                                                  'form': form})
    else:
        form = Category_form()
        return render(request, "category/add_category.html", {'form': form})



@login_required
@permission_required('is_superuser')
def edit_category(request, pk):
    if request.POST:
        data = request.POST
        form = Category_form(request.POST)
        if form.is_valid():
            category = Category.objects.filter(pk=pk).first()
            category.name = data['name']
            category.save()
            return render(request, "category/edit_category.html", {'good_alert': "Category updated successfully",
                                                                   'form':form})
        else:
            # redirect to the same page
            return render(request, "category/edit_category.html", {'bad_alert': "Failed to update category",
                                                                   'form':form})
    else:
        category = Category.objects.filter(pk=pk).first()
        form = Category_form()
        return render(request, "category/edit_category.html", {'form': form})



def show_categories(request):
    categories = Category.objects.all()
    return render(request, 'category/show_categories.html', {'categories': categories})

crowd_funding/templates/category/add_category.html
{% extends '../base.html' %}
{%block title%}Add Category{% endblock title%}
{% block contain %}
<div class="container">

<div class="row">
<div class="col-lg-3">

    </div>
    <div class="col-lg-6">
        <h1>Add Category</h1>
 <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" class="btn btn-primary btn-block" value="Add Category">
 </form>

    </div>
    <div class="col-lg-3">

    </div>


</div>
</div>
{% endblock contain %}

crowd_funding/templates/category/edit_category.html
{% extends '../base.html' %}
{%block title%}Add Category{% endblock title%}
{% block contain %}
<div class="container">

<div class="row">
<div class="col-lg-3">

    </div>
    <div class="col-lg-6">
        <h1>Edit Category</h1>
 <form method="POST" enctype="multipart/form-data">
     {% csrf_token %}
     {{form.as_p}}
     <input type="submit" class="btn btn-primary btn-block" value="Edit Category">
 </form>

    </div>
    <div class="col-lg-3">

    </div>


</div>
</div>
{% endblock contain %}

crowd_funding/templates/category/show_categories.html
{% extends '../base.html' %}
{%block title%}Add Category{% endblock title%}
{% block contain %}

<div class="container">
<h1>Categories</h1>
    <div class="row">
{% if request.user.is_superuser%}
    <div class="col-lg-3">

    </div>

    <div class="col-lg-6">

        <table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">id</th>
      <th scope="col">Name</th>
      <th scope="col">Edit</th>
    </tr>
  </thead>
  <tbody>
    {% for category in categories%}
    <tr>
      <th scope="row">{{category.pk}}</th>
      <td>{{category.name}}</td>
      <td><a class="btn btn-primary btn-block" href="{% url 'category:edit_category' category.pk%}">Edit {{category.name}}</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
        <a href="{% url 'category:add_category' %}" class="btn btn-primary btn-block">Add New Category</a>

    </div>

    <div class="col-lg-3">

    </div>
{%else%}

    {% for category in categories%}
    <div class="col-lg-3">

        <a href="/search/?search={{category.pk}}" class="btn btn-light m-4">{{category.name}}</a>
    </div>
    {% endfor%}

    {%endif%}

</div>
</div>
{% endblock contain %}